// This file is autogenerated by the backend pipeline. It should not be edited manually.

export type Equipment = {
  id: string;
  name: string;
  type: string;
  status: 'Operational' | 'Warning' | 'Offline';
  location: string;
  sensors: Sensor[];
  maintenanceLog: MaintenanceEvent[];
};

export type Sensor = {
  name: string;
  value: number;
  unit: string;
  history: { time: string; value: number }[];
};

export type MaintenanceEvent = {
  id: string;
  date: string;
  description: string;
  status: 'Completed' | 'Scheduled' | 'In Progress';
};
